### ISSUE TITLE
Sprint -> Ironsight behavior is severe 

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#102]
I mentioned this to you @MaxLebled already, but putting it here just so it's logged.

https://github.com/Facepunch/sbox-hc1/assets/22372616/3943fb35-db00-4ccd-86ca-95d186f020b1

**Comment by MaxLebled** [comment]
The transitions are now weakened to 20% of their strength while ironsights are active, does this look OK with you?

**Comment by DevulTj** [comment]
That's looking so much better!!
