### ISSUE TITLE
Weapon ADS modifications

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#109]
Will update as Rick gives me screenshots for how he wants weapons to look like in ADS.

**M4 should be like this**
![image](https://github.com/Facepunch/sbox-hc1/assets/22372616/4151c996-2b6d-4ac3-a01e-62d30ad87a0d)

**MP5 should be like this**
![image](https://github.com/Facepunch/sbox-hc1/assets/22372616/e3f72f4c-f899-4ffe-a5c1-30d9ee5fa0e2)

**USP should be like this**
![image](https://github.com/Facepunch/sbox-hc1/assets/22372616/c07d3eb9-d26d-438a-ab98-fd6c1ce3b088)

**Spaghelli should be like this**
![338930429-2fab33b5-a871-4639-9145-710a10ec38f7](https://github.com/Facepunch/sbox-hc1/assets/123948489/269b4b31-4e8f-410e-8e09-b03adc1ef36b)

**Comment by JasonO3D** [comment]
@MaxLebled 
Saw your latest check-in - will the MP5 ironsights be adjusted to look closer to the above reference images? 

Already a fantastic improvement, just looks like it needs pitching down to align with the rear sights, then moved down slightly. 👍

**Comment by MaxLebled** [comment]
Ah, I didn't look close enough and thought this was only about moving the weapon closer! I'll do the sights alignment adjust, thank you for pointing it out
