### ISSUE TITLE
Cash Grab

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#118]
**A team vs. team mode, 5v5.**

**Design**
_Spawn at team-based deployment, respawns enabled by default._

A **cash point** will be revealed to the players. This'll open up after 15-20 seconds (or more depending on map size). It'll open up until someone on any team picks up the cash and takes it to an **extraction point.**

**Cash Point** - defined in the map, cash points will spawn a bag of cash. It'll open up after some seconds, and players can grab it.

**Extraction Point** - revealed at the point when the cash point opens up, they're associated with the cash point, and any team can use any extraction point. You run up to it, and it'll take the cash. 

**Respawning Rules** - while there's a cash point open, respawns become disabled. Meaning you have to make your shots count, when a whole team dies, the other team has free reign to run to an extract point. 

All cash point events have a max time, which is reset when it's picked up for the first time, to give players enough time to extract, but not so much time that if you kill the whole enemy team they're dead for a long time.

After extraction, you'll receive cash for your team. The goal is to hit a set amount of cash. Winner is the first team to hit that amount, or have the most cash after 10 minutes.

**Art**
- Duffle Bag of Cash
- Loose Cash

**Code**
- Special inventory slot for holding items like the cash. We can reuse this for holding the drone or other large gadgets maybe.
- Dynamic respawn rules based on the game state (should be easy enough)
- Activate cash point, which activates its associated extract points. They need minimap icons, and markers.

**Comment by Metapyziks** [comment]
Sounds fun! Will you pick a loadout on respawn, or find guns around the map, or eat into your winnings to buy equipment?

**Comment by DevulTj** [comment]
I'm leaning towards something more cod/battlefield like where you can specify your loadout for free, but the idea of eating into your winnings sounds interesting, something to consider later on.

**Comment by JasonO3D** [comment]
With weapons being CS-style balanced at the moment, it's hard to say that user-made loadouts would be good. The M4 is just a powerhouse right now. Earnings-based sounds good

**Comment by DevulTj** [comment]
Earnings-based I think will be a bitch to balance, so it'd need a lot of attention
