### ISSUE TITLE
Molotov Grenade

### ISSUE THREAD

**Issue by RickGreeve** [Facepunch/sbox-hc1#13]
**Molotov**
- Art
Can be a simple glass bottle for now.

In the future this should have cloth, gibs for shatter and maybe liquid, how do we achieve this?
lighter asset for lighting the cloth?

![image](https://github.com/Facepunch/sbox-hc1/assets/125879070/0249f7d1-e668-4904-ac2f-e86a1715c1a3)

- Code
Fire nodes that spawn on the ground, and dissipate over time. They'll just play a fire particle effect. They hurt players inside them every X seconds that they're in a trigger.

- Design
Balance.

**Comment by DevulTj** [comment]
Nice stuff, just needs some FX that we can apply later
