### ISSUE TITLE
Late joiners not being assigned to a team

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#136]

**Comment by DevulTj** [comment]
Didn't work.

**Comment by Metapyziks** [comment]
For competitive do we want it like CS2 where only the original players can be on a team, and if they disconnect / reconnect, we put them back on the same team?

**Comment by DevulTj** [comment]
Yeah, I'd assume that's the case already with how playerstate acquisition is?

**Comment by Metapyziks** [comment]
Cool, let's give it a test today then.
