### ISSUE TITLE
Flashbang

### ISSUE THREAD

**Issue by RickGreeve** [Facepunch/sbox-hc1#14]
**M84 Stun Grenade** 
- Art
pin and latch need to be seperate for animation

![image](https://github.com/Facepunch/sbox-hc1/assets/125879070/a1a3bf4a-ee53-4f42-9ead-c666f6f8d611)

- Code
Based on if you're looking at the flashbang, will apply a screen effect (UI panel) which just fades in and out to white (or black, depending on if we're gonna add accessibility support for this), and a ringing sound.

- Design
Balance.

**Comment by kurozael** [comment]
Code aspect of this is done
