### ISSUE TITLE
Per weapon armor penetration

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#158]
We should expose a property to weapons so they can scale armor penetration on damage

**Comment by Metapyziks** [comment]
Some balance things to think about:

| Weapon | Target | Damage | Shots to Kill |
| --- | --- | --- | --- |
| USP | Body | 15 | 7 |
| USP | Head | 75 | 2 |
| USP | Helmet | 58 | 2 |
| M4 | Body | 20 | 5 |
| M4 | Head | 100 | 1 |
| M4 | Helmet | 78 | 2 |

I feel like ideally the USP should take more shots to kill against a helmet than an M4, and also more than the USP against a helmetless player.

**Comment by DevulTj** [comment]
Added some properties on the weapon resource to tweak these values. we should move the damage / speed reduction properties to the game resource too so it's nice and simple to edit everything.
