### ISSUE TITLE
Fresh Clone Fatal Error

### ISSUE THREAD

**Issue by FawasInteractive** [Facepunch/sbox-hc1#201]
Project cannot be opened, just downloaded it from the latest commit.

CPackedStore :: BuildHash Tables(:
VPK directory for 'C:\Users\user1\Downloads\sbox-hc1-main\Assets\maps\edinburgh\edinburgh.vpk' corrupt

![Image](https://github.com/user-attachments/assets/078fc1cd-2166-4f3a-bc83-97399d78cf15)

**Comment by DevulTj** [comment]
Looks like a LFS problem. How big is that VPK?

**Comment by FawasInteractive** [comment]
133 Bytes

**Comment by FawasInteractive** [comment]
> Looks like a LFS problem. How big is that VPK?

133 Bytes
