### ISSUE TITLE
Corpses lerp on respawn

### ISSUE THREAD

**Issue by Metapyziks** [Facepunch/sbox-hc1#60]
We're already calling `Transform.ClearInterpolation()` in `PlayerController.Teleport()`, maybe that's not working as intended? I had similar issues in Mazing.

**Comment by kurozael** [comment]
Probably fixed - will need re-testing on new Steam build to be sure but logic is sound now.

**Comment by DevulTj** [comment]
this was still happening, but after running ClearInterpolation on SetRagdoll, fixed it - so something to do with the interpolation code

**Comment by kurozael** [comment]
Seems like it may not still be getting cleared across the network as SetRagdoll is called in Respawn IIRC. Problem might be related to fact that transform is set by owner but it should get cleared when other players receive that. Will run some tests.

**Comment by DevulTj** [comment]
No longer an issue because we delete players and recreate them
