### ISSUE TITLE
USP, Knife too small in third person hands

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-hc1#69]

**Comment by RickGreeve** [comment]
![image](https://github.com/Facepunch/sbox-hc1/assets/125879070/7ef54ffa-955f-4531-af8c-b2481066459c)
![image](https://github.com/Facepunch/sbox-hc1/assets/125879070/35fccd86-bc49-4f1a-92c4-ea522882238c)
![image](https://github.com/Facepunch/sbox-hc1/assets/125879070/fc3eed1b-a76b-4418-b82f-0e7cb7ec5f65)

**Comment by DevulTj** [comment]
Legend
